### ISSUE TITLE
Backgrounded tasks in once script block execution until they finish

### ISSUE THREAD

**Issue by thieman** [gamechanger/dusty#380]
I'm trying to do something like this in an app spec:

```yaml
commands:
  once:
    - (apt-get update && apt-get install -y nodejs npm) &
    - ...
```

My expectation is that this line would work in the background and that the execution of the `once` command would not wait for it to complete. Instead, my container waits for this backgrounded task to complete before moving on to the `always` command during container startup.

Ping @jsingle who claims to know what's wrong here
