### ISSUE TITLE
Images with ENTRYPOINT defined don't work as apps

### ISSUE THREAD

**Issue by thieman** [gamechanger/dusty#435]
Report originally from Slack by @melkorm. Images with an `ENTRYPOINT` defined don't play nicely with Dusty's attempts to register the command file as a `COMMAND`, since this'll end up passing the command file to an entrypoint binary that has no idea what to do with it.

This app spec is a workaround to the problem with an image (in this case, `berngp/docker-zabbix`) which has an ENTRYPOINT defined. If you remove the `compose: entrypoint` key, you will see the error. This key is a workaround for now.

```yaml
image: berngp/docker-zabbix

host_forwarding:
  - host_name: local.zabbix.com
    host_port: 80
    container_port: 80

commands:
  always:
    - /bin/docker-zabbix run

compose:
  entrypoint: []
```

I think the solution here is to enforce the `commands` pattern for apps and always blow away the entrypoint if it is defined.
