### ISSUE TITLE
Optional branch as part of repo setting

### ISSUE THREAD

**Issue by torbjornvatn** [gamechanger/dusty#561]
I would be nice to have a way to specify a git branch for the `repo` settings in app/lib specs

E.g. 

``` yaml
repo:
  url: ssh://git@git.domain.com/path/to/repo
  branch: dev
```

Any chance for that happening?

(I should probably learn get better at Python, so I could send PRs for all these feature requests)
