### ISSUE TITLE
Compose 'ports' are ignored when host forwarding is set

### ISSUE THREAD

**Issue by marianzange** [gamechanger/dusty#589]
It seems like the `compose -> ports` section in an app spec is ignored, whenever `host_forwarding` is set. I have a use case, where I need host forwarding as well as mapping an additional port. Is ignoring additional ports a design decision or is it a bug?

Here's an example snippet from my app spec:

```yaml
[...]

host_forwarding:
  - host_name: www.project.local
    host_port: 80
    container_port: 8000

compose:
  ports:
    - "10100:10100"

[...]

```
