### ISSUE TITLE
Ability to map multiple domains to same container

### ISSUE THREAD

**Issue by apeace** [gamechanger/dusty#607]
I have a use-case where I'd like to be able to have something like this in my app config:

```yaml
host_forwarding:
  - host_name: sub1.local.com
    host_port: 80
    container_port: 8000
  - host_name: sub2.local.com
    host_port: 80
    container_port: 8000
```

Essentially, I just want two different domains in `/etc/hosts` to map to the same container. Of course, my application is only running one process and listening on one port (8000).

I was able to get this working with the following patch:

```
diff --git a/dusty/compiler/port_spec/__init__.py b/dusty/compiler/port_spec/__init__.py
index 50218d7..0560624 100644
--- a/dusty/compiler/port_spec/__init__.py
+++ b/dusty/compiler/port_spec/__init__.py
@@ -29,8 +29,8 @@ def _add_full_addresses(host_forwarding_spec, host_full_addresses):

 def _add_container_ports(host_forwarding_spec, container_ports):
     container_port = host_forwarding_spec['container_port']
-    if container_port in container_ports:
-        raise ReusedContainerPort("{} has already been specified and used".format(container_port))
+    #if container_port in container_ports:
+    #    raise ReusedContainerPort("{} has already been specified and used".format(container_port))
     container_ports.add(container_port)

 def _add_stream_host_port(host_forwarding_spec, stream_host_ports):
```

That's not to say this is the best way to make the change--just a hack/proof of concept that demonstrates that it can be done.
